### ISSUE TITLE
Support for ALTO 3.0

### ISSUE THREAD

**Issue by M3ssman** [filak/hOCR-to-ALTO#15]
Are there any plans to integrate transformation from hOCR to ALTO 3.0 / 3.1 ?

**Comment by M3ssman** [comment]
Looks like the only required change is a shift in the namespace declaration? Or do I miss something? I could contribute if it's okay?

**Comment by filak** [comment]
Yes, you can contribute.

**Comment by M3ssman** [comment]
see https://github.com/filak/hOCR-to-ALTO/pull/16
