### ISSUE TITLE
alto2hocr: Support word confidence values in export

### ISSUE THREAD

**Issue by zuphilip** [filak/hOCR-to-ALTO#18]
In ALTO we have word confidences `WC` like this
```xml
<TextLine HEIGHT="52" WIDTH="674" VPOS="53" HPOS="5">
  <String WC="0.3212499917" CONTENT="articles" HEIGHT="37" WIDTH="127" VPOS="54" HPOS="5"/>
  <SP WIDTH="20" VPOS="57" HPOS="133"/>
  <String WC="0.6499999762" CONTENT="dans" HEIGHT="35" WIDTH="82" VPOS="57" HPOS="154"/>
  <SP WIDTH="21" VPOS="55" HPOS="237"/>
  <String WC="0.5533333421" CONTENT="les" HEIGHT="37" WIDTH="45" VPOS="55" HPOS="259"/>
  <SP WIDTH="18" VPOS="69" HPOS="305"/>
  <String WC="0.6327272654" CONTENT="capillaires" HEIGHT="49" WIDTH="208" VPOS="56" HPOS="324"/>
  <SP WIDTH="21" VPOS="53" HPOS="533"/>
  <String WC="0.4550000131" CONTENT="de" HEIGHT="37" WIDTH="41" VPOS="53" HPOS="555"/>
  <SP WIDTH="19" VPOS="66" HPOS="597"/>
  <String WC="0.5566666722" CONTENT="nos" HEIGHT="23" WIDTH="62" VPOS="66" HPOS="617"/>
</TextLine>
```
from https://digi.bib.uni-mannheim.de/~stweil/ocr-praxis/Testseiten/alto/417576986_0031.xml . This should be exported in hocr as `x_wconf` parameter with a range from 0 to 100:
```html
            <span class="ocr_line" id="line_d1e31" title="bbox 5 53 679 105">
               <span class="ocrx_word" id="word_d1e32" title="bbox 5 54 132 91; x_wconf 32.12499917">articles</span>
               <span class="ocrx_word" id="word_d1e34" title="bbox 154 57 236 92; x_wconf 64.99999762">dans</span>
               <span class="ocrx_word" id="word_d1e36" title="bbox 259 55 304 92; x_wconf 55.33333421">les</span>
               <span class="ocrx_word" id="word_d1e38" title="bbox 324 56 532 105; x_wconf 63.27272654">capillaires</span>
               <span class="ocrx_word" id="word_d1e40" title="bbox 555 53 596 90; x_wconf 45.50000131">de</span>
               <span class="ocrx_word" id="word_d1e42" title="bbox 617 66 679 89; x_wconf 55.66666722">nos</span>
            </span>
```

**Comment by filak** [comment]
OK, please confirm that according to hOCR spec:

properties-format = key-value-pair *(*whitespace semicolon *whitespace key-value-pair)

there should be whitespace before the semicolon:

title="bbox 617 66 679 89 **;** x_wconf 55.66666722"

**Comment by zuphilip** [comment]
I think that the asterisk in this expression are for the following part, i.e. read as `property-format ` is a `key-value-pair` possibly followed by 0, 1, or multiple expressions of the form ( possibly 0, 1, or multiple `whitespace`(s) followed by a `semicolon` followed by possibly 0, 1, or multiple `whitespace`(s) followed by a `key-value-pair`).

Thus, AFAIU all variants are possible without whitespaces, only before, only afterwards, both and always it can also be more than one whitespaces. But @kba is the expert in these formatting questions.

The variant I used above is the one produced by Tesseract, e.g. https://github.com/kba/ocr-fileformat-samples/blob/master/samples/hocr/1.1/417576986_0013.hocr

**Comment by filak** [comment]
OK, this should be fixed.

**Comment by zuphilip** [comment]
Thank you very much! I will test the DEV version with some examples.

BTW it might be easier and cleaner to work with a special dev branch instead of a temporary folder. Such a dev branch can then been merged after testing is fine.
