### ISSUE TITLE
Decrease redundancy of the various hocr__alto files

### ISSUE THREAD

**Issue by zuphilip** [filak/hOCR-to-ALTO#19]
Currently, there are four hocr__alto transformation files for the different versions of alto 2.0, 2.1, 3.0, 4.0. However, they are for most parts the same and share a lot of code. This makes changes in this transformation(s) more cumbersome to update and maintain.

There exists `import` and `include` in XSLT which might improve this situation. I would envision a main transformation XSLT which then can be imported/included in another one where the namespace is fixed to another version.

**Comment by filak** [comment]
All the versions have been synced today. It is not a lot of code. 

We can have only 1 file maybe ...

But how would you like to control the output ALTO version ?

- if using xsl:param (with fallback to the newest ALTO version) is it feasible/friendly enough for users ?

Or we can have 4 (now) files + 1 more with shared code

- would this be less or more cumbersome ?

**Comment by zuphilip** [comment]
I was thinking about your second option (1 main file + several smaller files dealing with the namespace and any version specific transformation) with xsl:import or xsl:include. But I haven't used these before and therefore I am not sure how this exactly could work. Maybe we could give it a try?

Another, maybe easier, solution would be to have one master file, e.g. currently hocr__alto4.0, and generate the others from this with a little script by replacing the namespace and schema location.

**Comment by filak** [comment]
I am not sure if it is worth of the effort...

**Comment by filak** [comment]
Or we can just provide the newest version as **hocr__alto.xsl** which would support the newest ALTO version and keep that file up-to-date regularly so users can rely on that file...

And I can then maintain the older versions as necessary... (?)

**Comment by zuphilip** [comment]
Okay, that sounds also fine. I would also suggest then to make another subsection in the README titled as e.g. "Older schema versions" and link the other versions there only.

**Comment by filak** [comment]
I think that it is important for users to realize that there are multiple versions of ALTO - and we provide this information transparently by appending the version identifier to the XSL files. 

The README seems clear enough for now so am closing this issue...
