### ISSUE TITLE
problem with Alto 2.0 and LXML

### ISSUE THREAD

**Issue by jscancella** [filak/hOCR-to-ALTO#21]
Hello, I am hoping you can help me with a problem I am having. I am trying to convert from HOCR to ALTO 2.0. I am using python's LXML library. However, when it tries to compile the hocr__alto2.0.xsl it gives the error `lxml.etree.XSLTParseError: xsltCompilePattern : failed to compile '*:span[@class='ocrx_word']'`

Any idea what could be causing this problem? I have attached the file I am trying to convert in case that helps.
[0001_xStart0_xEnd937.hocr.txt](https://github.com/filak/hOCR-to-ALTO/files/5550087/0001_xStart0_xEnd937.hocr.txt)

**Comment by filak** [comment]
The schema is well-formed according to my xml editor.

And when using Saxon HE parser (https://www.saxonica.com/download/java.xml) the transformation just works fine. 

Are you sure your parser supports XSLT 2.0 ?

**Comment by filak** [comment]
> Are you sure your parser supports XSLT 2.0 ?

It seems not:

https://lxml.de/xpathxslt.html

> lxml supports XPath 1.0, XSLT 1.0 and the EXSLT extensions through libxml2 and libxslt in a standards compliant way.

**Comment by jscancella** [comment]
ok thank you for your help
