### ISSUE TITLE
alto to text: too many spaces

### ISSUE THREAD

**Issue by jbarth-ubhd** [filak/hOCR-to-ALTO#22]
Example alto excerpt:

```xml
<TextLine><String CONTENT="Wappen:"/><SP/><String CONTENT="Heimstatt;"/><SP/><String CONTENT="Heimstatt,">... ...
```
converts to text
```
Wappen:␣␣Heimstatt;␣␣Heimstatt,␣␣Neipperg,␣␣Gemmingen ... ...
```

**Comment by filak** [comment]
I am not the author of this script, it is @kba

I can see that:

- SP tag is being replaced with a space 

      <xsl:template match="*[local-name()='SP']">
            <xsl:text>&#x20;</xsl:text>
      </xsl:template>

- and CONTENT is being appended with another space
 
         <xsl:value-of select="@CONTENT"/><xsl:text>&#x20;</xsl:text>

So that is why you see 2 spaces in your output - so maybe I could remove the latter ?

**Comment by jbarth-ubhd** [comment]
@kba asked me to open a ticket here :-)

**Comment by filak** [comment]
Fine, does he suggest a fix ?

**Comment by kba** [comment]
> I am not the author of this script, it is @kba

Sorry, I didn't remember that, thanks for checking though.

>    `<xsl:value-of select="@CONTENT"/><xsl:text>&#x20;</xsl:text>`

Removing this one seems like the right solution ~~, but I'll have a look myself.~~ yes that was the problem.
