### ISSUE TITLE
Include font information in hOCR

### ISSUE THREAD

**Issue by ghost** [filak/hOCR-to-ALTO#6]
I have used pdfalto to create an xml file. This file is transformed to hOCR using the alto2hocr.xsl functionality. However, the font information of each word/line is lost in the process. Is there a way to include this in the output hOCR?

**Comment by filak** [comment]
Would you be so kind and provide a link to your ALTO file?  I will try to fix the XSLT.

**Comment by NaguiBL** [comment]
Hi filak,
Here is an example of ALTO file we get from pdfalto.
I've turned it into a txt file as xml format is not supported for attached files.

[test_document.txt](https://github.com/filak/hOCR-to-ALTO/files/2094414/test_document.txt)

**Comment by filak** [comment]
Thanks. Sorry for the delay.

I can put the font info in **x_font** attribute: http://kba.cloud/hocr-spec/1.2/#x_font

Are you OK with that?

**Comment by ghost** [comment]
Yes that would be perfect!

**Comment by filak** [comment]
Looking at your ALTO file... There are more attributes which might be necessary to convert/preserve, ie: 

`<TextStyle ID="font0" FONTFAMILY="Times New Roman,Bold" FONTSIZE="12.000" FONTTYPE="sans-serif" FONTWIDTH="proportional" FONTCOLOR="#WWWWWW" FONTSTYLE="bold"/>`

Could you please describe your use case? How do you plan to use the HOCR files?

**Comment by ghost** [comment]
We would like to have as much information about a word as possible, to use in neural networks to predict certain tags of a word. (Named Entity Recognition)

**Comment by filak** [comment]
OK. Why do you need HOCR, can't you just use the ALTO XML ? It is more granular than hOCR, you can parse it easily to input that you need...

**Comment by ghost** [comment]
We use the hOCR also for other purposes in our project, so we cannot use the ALTO XML format unfortunetly.

**Comment by filak** [comment]
No problem. Though according to hOCR spec (http://kba.cloud/hocr-spec/1.2/#font-properties) I can convert only the following attrs:

- FONTFAMILY => x_font
- FONTSIZE => x_fsize

What would be the ideal input for your system apart from hOCR ?

**Comment by filak** [comment]
Anyway, I have added the x_font & x_fsize to the transformation (https://github.com/filak/hOCR-to-ALTO/commit/f05740cb71a162587027936934d4c6a16a2898df)
