### ISSUE TITLE
Question alto2hocr.xsl

### ISSUE THREAD

**Issue by amitoh** [filak/hOCR-to-ALTO#9]
I don't have much experience with XMLs and I was wondering how should I handle:
xmlns:mf="http://myfunctions" ?

what additional services are required in order to get the xsl to work?

**Comment by filak** [comment]
All the stylesheets in hOCR-to-ALTO uses XSLT version 2.0 - so what you need is a XSLT processor supporting XSLT 2.0 - ie. https://stackoverflow.com/questions/515979/java-xslt-processors-supporting-xpath-2-0 

For personal use I prefer Saxon-HE:
https://www.saxonica.com/download/java.xml

**Comment by amitoh** [comment]
thanks for the reply, sorry for the private debug session..

Using Saxon-HE@9.9.0-2 and I'm getting the following error:
_javax.xml.transform.TransformerConfigurationException: The first argument to the non-static Java function 'getBox' is not a valid object reference._

**Comment by filak** [comment]
I have tried http://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/ - SaxonHE9-9-1-1J.zip

It just works when running like this:
java -jar saxon9he.jar -s:input.alto.xml -xsl:alto2hocr.xsl -o:output.hocr.html

How are you trying to call the transformation ?

**Comment by amitoh** [comment]
i'm using the Saxon library Java API (from maven repository),

this is the code i'm running:



        Source xmlSource = new StreamSource(IOUtils.toInputStream(altoXmlText, "UTF-8"));
        Source xsltSource = new StreamSource(ClassLoader.getSystemResourceAsStream("alto2hocr.xsl"));
        StringWriter sw = new StringWriter();
        Result result = new StreamResult(sw);
        TransformerFactory transFact = new TransformerFactoryImpl();
        Transformer trans = transFact.newTransformer(xsltSource);

        trans.transform(xmlSource, result);

**Comment by filak** [comment]
Well, I do not know, maybe this might help you ?
http://stackoverflow.com/questions/29514919/ddg#29514920

**Comment by filak** [comment]
I assume your Java code uses XSLT 1.0 processor and that is why it fails on the 2.0 stylesheet.
